### ISSUE TITLE
how to generate Date to DTO type string($date-time)

### ISSUE THREAD

**Issue by kyklovod** [cyclosproject/ng-swagger-gen#106]
How to modify templates or is it possible to generate 
 type **string | Date** if api spec is defined as string($date-time) or string($date)

**Comment by luisfpg** [comment]
See #36.
Even if you generate the types as `string | Date`, when setting a date, you'd need to preprocess the object graph before sending to the server, to convert Dates to strings. Same for incoming objects, you'd need to replace all strings to Dates.
Such operation is out of scope for `ng-swagger-gen`.
Why don't you work with dates as strings, and just format / parse them when needed?
Here is an example: https://github.com/cyclosproject/cyclos4-ui/blob/master/src/app/shared/date-field.component.ts . In the example, there's an internal `FormControl` (it uses reactive forms) that holds the value parsed as Date. The [ngx-bootstrap datepicker](https://valor-software.com/ngx-bootstrap/#/datepicker), which works with Dates, uses the internal control, instead of the regular `FormControl`, which works with strings.
