### ISSUE TITLE
ng-swagger-gen Https SSL Connectivity

### ISSUE THREAD

**Issue by jivel** [cyclosproject/ng-swagger-gen#127]
I have a problem, I try to execute

**$ ./node_modules/.bin/ng-swagger-gen**
Error reading swagger location https://localhost:8090/api/v2/api-docs: Error: Error downloading https://localhost:8090/api/v2/api-docs
self signed certificate

**Comment by luisfpg** [comment]
Can you try setting the environment variable `NODE_TLS_REJECT_UNAUTHORIZED=0` before running the generator?

**Comment by luisfpg** [comment]
Closing this due to lack of feedback

**Comment by tbandixen** [comment]
I now have a similar error:
```$ ng-swagger-gen -i http://localhost:5500/swagger/v1/swagger.json -o src/app/core/api
Error reading swagger location http://localhost:5500/swagger/v1/swagger.json: Error: Error downloading https://localhost:44308/swagger/v1/swagger.json
unable to verify the first certificate
Done in 0.45s.```

Its the IIS Express local development certificate, Trusted for Machine and User (Windows 10 PC)

**Comment by tbandixen** [comment]
Setting the env variable didnt change anything

**Comment by jdimmerman** [comment]
In case others come here - you do this on the client, not server.

Example:
```
NODE_TLS_REJECT_UNAUTHORIZED=0 npm run gen-api http://localhost:5000/swagger/1.0/swagger.json
```

**Comment by begrs** [comment]
This is highly discouraged by npm itself!  
If you work in a business context you should not use it due to security concerns (raised by multiple parties)

The correct way to do it is https://nodejs.org/api/cli.html#node_extra_ca_certsfile
which I described here: https://github.com/cyclosproject/ng-openapi-gen/issues/167 (although my post is for ng-openapi-gen) but it currently has a bug. Please support my bug ticket so it is finally possible to use ng-swagger-gen and ng-openapi-gen securely in a development setting.

**Comment by AbhijeetWarade** [comment]
Error reading swagger location https://localhost:44393/swagger/v1/swagger.json: Error: Error downloading https://localhost:44393/swagger/v1/swagger.json
self signed certificate

any solution for this

**Comment by folabi-ahn** [comment]
Do you guys find a fix for this issue of self signed certificate ?
