### ISSUE TITLE
Service name collisions

### ISSUE THREAD

**Issue by krojew** [cyclosproject/ng-swagger-gen#152]
Generated service class names can cause collisions with other services named the same (especially from another dependency, which is outside control). To solve this, two config options can be handy:

- an option to provide the services in the generated module, instead of 'root'
- an option to add name prefix

**Comment by GeorgeKnap** [comment]
name prefix is already in configuration schema. It's called `prefix`.

> `prefix`: A prefix to the generated global classes, such as Configuration and Module. Defaults to 'Api', so the default generated files are ApiConfiguration and ApiModule.

**Comment by krojew** [comment]
What I meant was a prefix for the actual services.

**Comment by luisfpg** [comment]
A prefix for service names can be added in the configuration.

**Comment by tflanitzer** [comment]
How? At least it is not mentioned in the readme.

Or did you mean that this enhancement will be added. If so, I am also keenly awaiting it. ;)

**Comment by krojew** [comment]
Possibility of providing in the generated module is also a nice thing to have.

**Comment by luisfpg** [comment]
Sorry, this was never implemented due to lack of resources.
If you need to change the `providedIn` on generated services, just override the templates (copy the entire `templates` folder to your project and set the `templates` config pointing to it), and edit the `service.mustache` file.
Closing it for now.
