### ISSUE TITLE
Make models as classes a command line option

### ISSUE THREAD

**Issue by jcjveraa** [cyclosproject/ng-swagger-gen#163]
First of - thanks for making this! Makes my life easier in my fairly straighforward Angular + api project and up to now it 'just works' (once I had figured out how to run the commands having never done that before :).

In #25 you changed from classes to interfaces, and I think it makes sense in quite a few cases. However for my use case, I actually want classes as I need empty instances of the models sometimes, e.g. when setting up to Post something. 

Doing it the way you suggested, I get issues with 'fake instantiation' (e.g. `item: myModel = {};`) as `item` now is a 'true' value without the necessary properties (and TSLint complains about this usage anyway). This gives me issues when trying to bind a ngModel to it for instance.

I've now simply 'hacked' the object.mustache file and changed 'interface' to 'class', but I guess it should be quite doable to make this a command line option. Would you support that, or am I missing some other (better) way of achieving the same goal?

**Comment by luisfpg** [comment]
Having them as interfaces is actually correct, because when a JSON is received, we don't instantiate new objects on every model (i.e., `person.address instanceof Address == false`).
Also, having interfaces instead of classes has the advantage that they don't generate any JS code, thus, reducing the code size.
In that sense, generating classes and not interfaces was a mistake in the beginning, and not in the radar for the project.

> This gives me issues when trying to bind a ngModel to it for instance.

What kind of instances? ngModel just reads properties, and works with any object.

> I've now simply 'hacked' the object.mustache file and changed 'interface' to 'class'...

You can copy the full templates folder to your project, set the `templates` option in the configuration file to point to it and customize the template if you need to.

**Comment by ealib** [comment]
@jcjveraa Maybe you should map plain objects to class instances with e.g. [class-transformer](https://github.com/typestack/class-transformer).

**Comment by Wayne-Mather** [comment]
@jcjveraa I just create helper functions like below. Returns to me a fully hydrated object based on the interfaces and also supports an object heirachy. I would love the framework to generate this for me, but I don't find it a big deal to modify if the API surface changes.

It also gives me only 1 point in to my code base where my objects are created.

// XXX would be the interface
createXXX(): XXX {
   let model: XXX = {}; // or let model = {} as XXX;
   model.SubObject = {};
   return model;
}

**Comment by luisfpg** [comment]
Closing this. If further questions arise, feel free to comment again and I'll reopen it.
