### ISSUE TITLE
feedback

### ISSUE THREAD

**Issue by robert-king** [cyclosproject/ng-swagger-gen#170]
hey good job on this ng-swagger-gen.

bit of feedback:

1. I came across an api with a lowercase i instead of a capital i:
DELETE /api/Admin/Companies/{companyId}/settings/domains/{domainid}
but the param required is domainId (capital i).

the generator will produce:
`this.rootUrl + `/api/Admin/Companies/${params.companyId}/settings/domains/${params.domainid}`,
`

which gives a compiler error that domainid doesn't exist on params (only domainId does).
- unfortunately i don't have access to change the backend api.

2. - it would be nice to be able to prefix the service names, e.g. companiesService already exists in my angular app, so i'd rather call these 
class CompaniesService extends __BaseService
instead:
class APIPREFIXCompaniesService extends __BaseService

3. I have one api that uses inheritance. It produces something like:
```
export interface ArticleData extends BasePageData {
  blockList?: Array<BaseBlockData>;
}

export interface BaseBlockData {
  blockType?: string;
}

```

Unfortunately, BaseBlockData could be anything, and i don't get any of the models that extend BaseBlockData, so for example if i did a discriminated union type and switch type on blockType, i'm not able to have type safety or even have models for what the block type is. So basically i'm going without type safety for this certain api. Once again i don't have access to the backend on this one.

Other than that it's working well! thank you :)

**Comment by luisfpg** [comment]
1. This is an error with the swagger definition. There's nothing we could do about it.

2. This can be reported as a new issue. It could be implemented as a new confirmation option `servicePrefix`. However, with the advent of (ng-openapi-gen)[https://github.com/cyclosproject/ng-openapi-gen], I'm mostly just applying PR's from the community in ng-swagger-gen. And, interesting, ng-openapi-gen already supports this.

3. Probably the sub-interfaces are being skipped because they are not referenced. You could set the `ignoreUnusedModels` flag in the configuration file to false to generate them anyway.

**Comment by robert-king** [comment]
Thanks a lot. https://github.com/cyclosproject/ng-openapi-gen looks interesting, will keep openapi in mind for my next project, thanks a lot
