### ISSUE TITLE
Support responseType: blob

### ISSUE THREAD

**Issue by KnutHaraldR** [cyclosproject/ng-swagger-gen#182]
In my API spec I have

`schema":{"format":"binary","type":"blob"}}`

It should generate like this:

`responseType: 'blob'`

Instead I get this:

`responseType: 'json'`

**Comment by luisfpg** [comment]
According to the [swagger specification](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md#data-types), the only valid types are:
- integer
- number
- string
- boolean
- file (for parameter / response)

**Comment by KnutHaraldR** [comment]
Ok, "file" works as well as "blob" in my Api, so it does the job.

**Comment by rubimadi** [comment]
Hi,
I have a REST API resource that resturns a stream (PDF and Excel). The generated code specifies for this resource json as response type with null as a return type for the generated method.

`  GetReportResponse(params: ReportService.GetReportParams): __Observable<__StrictHttpResponse<null>> {
...
`

`let req = new HttpRequest<any>(
      'POST',
      this.rootUrl + `/api/Report/GetReport`,
      __body,
      {
        headers: __headers,
        params: __params,
        responseType: 'json'
      });`

`return this.http.request<any>(req).pipe(
      __filter(_r => _r instanceof HttpResponse),
      __map((_r) => {
        return _r as __StrictHttpResponse<null>;
      })
    );`

` GetReport(params: ReportService.GetReportParams): __Observable<null> {
    return this.GetReportResponse(params).pipe(
      __map(_r => _r.body as null)
    );
  }`


Calling the generated method doesn't work like this. After I change manually the response type to blob and the return type of the method to Blob. It works.

Is it possible to generate it like this?

BTW the Angular class HttpRequest accepts as responseType 'arraybuffer', 'blob', 'json' and 'text'
https://angular.io/api/common/http/HttpRequest#responseType

This confuses me since the swagger specification doesnt specifies blob as a type

Best regards

**Comment by giuliovivian** [comment]
I have same problem,
my dotnet core api produces a "text/csv" response but the generated angular service have responseType: 'json' instead of 'blob' or 'file'.
(If I manually change 'json' with 'blob' it works correctly, but i can't do it manually every time i generate it)
