### ISSUE TITLE
Invalid array handling in multipart/form-data

### ISSUE THREAD

**Issue by dmushkov** [cyclosproject/ng-swagger-gen#184]
There is problem when given api method consumes multipart/form-data and there is parameter which is of type array of strings ... 

example 
**in model** 
 arrayofstringparam is Array[string]
 
 __formData.append('arrayofstringparam', JSON.stringify(params.arrayofstringparam));

in that way api server is called in wrong way and arrayofstringparam is null

it should be 

 const k =`${params.arrayofstringparam}`

 __formData.append('arrayofstringparam', k);

any advice ?

**Comment by luisfpg** [comment]
Please, test the code in the https://github.com/cyclosproject/ng-swagger-gen/tree/multipart_array branch. If ok, I'll merge it in the next release.

**Comment by Lonli-Lokli** [comment]
@luisfpg I believe there still is an issue with arrays, same in ng-openapi-gen I think.

Assume we have this data with nested array
Person {name: string; Addresses: {street: string}[]}

It will be send to API as JSON instead of sending
Person.Addresses[0].streat = 'Picadilly'

As in .NET JSON formatter is not used for deserialization, it will lead to failing model binding.
