### ISSUE TITLE
Generate all the models in a single file

### ISSUE THREAD

**Issue by ferrarikarthik** [cyclosproject/ng-swagger-gen#207]
Hi,
 Currently, for each model, a new model.ts file is generated. 
i.e - api/models/modeln.ts: One file per model file is generated here. Enumerations are also correctly generated;
This is fine if the number of models are small. But when we have more models(this is the case in most of the Projects), equal number of model.ts files are created in the client side. This is very difficult to maintain. So, please provide the option where we can specify if all the models are created in single file or each separate file.
Please add the functionality of creating all the models in a single ts file.

**Comment by luisfpg** [comment]
> This is very difficult to maintain

Why do you need to maintain generated files? See #24

**Comment by ferrarikarthik** [comment]
@luisfpg , when we have more than 50 models in our API, it is always better to have a single model.ts file with all the models in it, instead of creating 50 files in the client side. And of course it is easier if we could also generate single file. We will always have the existing feature of generating one file per model. We can have a property in Configuration file, "generateSingleModelFile", by default it will be false, so existing things will work as expected. Those who wants single file, can set the value to true and it generates 50 models in one file.

**Comment by luisfpg** [comment]
> when we have more than 50 models in our API, it is always better to have a single model.ts

Better is subjective. I don't see it as better. Actually, as worst. Angular style guide recommends a single component per file: https://angular.io/guide/styleguide#single-responsibility. There's also a ts-lint rule to limit the max numbers of classes per file: https://palantir.github.io/tslint/rules/max-classes-per-file/.

FYI, We work with a file that has a total of 649 models and 50 services: https://github.com/cyclosproject/cyclos4-ui/blob/master/src/openapi/cyclos-openapi.yaml (we have switched to OpenAPI / https://github.com/cyclosproject/ng-openapi-gen, that's why ng-swagger-gen is in maintenance-only mode). Despite the size, we never ever thought about generating a single file with all models. Indeed there is a `models.ts` file which just re-exports them all.

So, closing this as invalid.
