### ISSUE TITLE
generate models as interfaces instead of classes

### ISSUE THREAD

**Issue by josh-sachs** [cyclosproject/ng-swagger-gen#25]
The generator currently produces model classes, however I think that these are ideal candidates for Typescript interfaces as they are only used for type checking.

As classes, they are actually output as function definitions during transpile. 

As interfaces they would be omitted from the output, resulting in a smaller distribution.

Maybe an ng-swagger-gen.json configuration option would be possible?

**Comment by luisfpg** [comment]
This would be nice, actually.
Even if it is backwards-incompatible, because it prevents code like `const model = new Model()`, which should then be written as `const model: Model = {}`, the benefit of having a smaller generated code pays off.
I don't think it is worth putting a configuration option, because any object received from the server will not have the expected class (prototype) anyway, as they are just plain JSON objects.

If you need a temporary workaround, you can copy the `templates` folder from `ng-swagger-gen` to some path in your project, set `templates` to point to it in the configuration file and just change 1 word in `object.mustache`: just replace `class` by `interface` and you're ready to go.

**Comment by remisture** [comment]
This would be nice to have.
