### ISSUE TITLE
How to access headers of a response?

### ISSUE THREAD

**Issue by mrKremt** [cyclosproject/ng-swagger-gen#33]
Some of the code could depend on additional data provided with the custom headers in the responses. 

After the upgrade to the 0.9v it doesn't seem to be a way to access the same data, or the headers in general. Please have a look at the following portion of code:

```javascript
newUsers.hasMoreResults = users.headers.get('x-has-next-page') === 'true';
```

and its related error:

```javascript
Property 'headers' does not exist on type 'UserResult[]'.
```

I tried to obtain the entire response following the [Angular documentation for the HTTPClient](https://angular.io/guide/http#reading-the-full-response) but looking deeper at the source of the generated services, it doesn't seem to be a way to get the headers, because they always return the body of the response:

```javascript
searchUsers(params: UsersService.SearchUsersParams): Observable<UserResult[]> {
    return this.searchUsersResponse(params).pipe(
      map(_r => _r.body)
    );
  }
```

What's the best way to get them?

**Comment by luisfpg** [comment]
Yes, and getting the response headers is very important!
That's why all services have 2 versions of each method: one that return `Observable<Result>` and the other one returning `Observable<HttpResponse<Result>>`.
Even in your example, you see that `searchUsers` calls `searchUsersResponse`.
You just have to call the `searchUsersResponse` and you'll get the `HttpResponse` object.

**Comment by mrKremt** [comment]
Ok, thanks a lot for your quick response
