### ISSUE TITLE
Generation of API removes previously generated API from different domain

### ISSUE THREAD

**Issue by wernerva** [cyclosproject/ng-swagger-gen#34]
Here' the scenario. I have several API's that I want to generate clients for. I want to bundle all of them into one shared module. When I run the ng-swagger-gen command the first time, all is well and the generator works as advertised.

As soon as I run the command again, this time specifying a different API's swagger endpoint, it removes the  initial service API client and modules.

I want all of the APIs without having to specify a separate folder for each.

**Comment by luisfpg** [comment]
The only way you can accomplish this is having several configuration files, each pointing the generation to a separated directory.
It was missing in the README, and I've updated it now, so you can refer to https://github.com/cyclosproject/ng-swagger-gen#using-a-configuration-file.

Unfortunately it is not possible to "merge" several generations to the same output folder. But, it shouldn't be a problem, because you then import the multiple modules and each one export their own services.

**Comment by wernerva** [comment]
As a work-around I generated the services each into their own directory
then copied them all into a single directory and merged the comment imports
etc.

Each service overrides the base url with it's own value configured in the
environments object.

**Comment by luisfpg** [comment]
Ok, just keep in mind that if the swagger ever changes, you'll have to manually copy again, which can be a burden for maintenance (if the swagger is expected to evolve).
