### ISSUE TITLE
'Unhandled model type for ...' error

### ISSUE THREAD

**Issue by dimitriy-k** [cyclosproject/ng-swagger-gen#4]
when definition object has no `type` property it fails

```
"TestResponse": {
            "properties": {
                "objectId": {
                    "type": "string"
                },
                "message": {
                    "type": "string"
                }
            }
        },
```

Possible solution:
extend model.type check to `else if (model.type === 'object' || typeof model === 'object') {`

**Comment by luisfpg** [comment]
On the [Swagger specification](http://swagger.io/specification/) it states that objects should have a type = object, so the example given is not in conformance to the specification.
Maybe some other tooling is lenient regarding this, but I don't think we should support it.
For example, other data types, such as string, would also have typeof model == 'object', since it is an object with a type: string property.

**Comment by luisfpg** [comment]
Actually I was checking the petstore example at https://raw.githubusercontent.com/OAI/OpenAPI-Specification/master/examples/v2.0/json/petstore.json and really there are cases of object models without defining type: object. Reopening...
