### ISSUE TITLE
Package generated client as a library

### ISSUE THREAD

**Issue by egwepas** [cyclosproject/ng-swagger-gen#49]
Hello,

I dislike the fact that i have to mix generated sources with normal sources. I'd like to generate the client in a separate project (from my backend-maven project) and release it as an angular dependency.

Can you recommand a way to do it ?
Maybe it could be a nice option to the generator to generate a "ready-to-package" project.

Thanks

**Comment by luisfpg** [comment]
There's no plan to implement a "ready-to-package" project.
I have tried to implemente a POC for such a library, and it worked, with some quirks.
So, create a new project, it contains:

- The swagger definition file. Say `api.json`
- The `ng-swagger-gen.json`file, pointing to `api.json`
- The `package.json` file:
```json
{
  "name": "api-lib",
  "version": "0.0.1",
  "scripts": {
    "build": "ng-swagger-gen && tsc && cp -rf package.json dist",
    "link": "npm run build && cd dist && npm link"
  },
  "dependencies": {
    "@angular/core": "^5.2.9",
    "@angular/common": "^5.2.9",
    "rxjs": "^5.5.8"
  },
  "devDependencies": {
    "ng-swagger-gen": "^0.11.2",
    "typescript": ">=2.4.2 <2.7"
  }
}
```
- The `tsconfig.json` file:
```json
{
  "compileOnSave": false,
  "angularCompilerOptions": {
    "preserveWhitespaces": false
  },
  "compilerOptions": {
    "outDir": "dist",
    "baseUrl": "src",
    "sourceMap": true,
    "declaration": true,
    "moduleResolution": "node",
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "skipLibCheck": true,
    "target": "es5",
    "typeRoots": [
      "node_modules/@types"
    ],
    "lib": [
      "es2016",
      "dom"
    ]
  }
}
```

Then, just run `npm run link`. It will link the module globally, so you can just run `npm link api-lib` from your client module to use it.
Following this: https://github.com/npm/npm/issues/10996 It will compile the TypeScript files to `dist`, then copy the `package.json` file to there and build from there, so you can import models and services directly. Something like `import { Model } from 'api-lib/models';` instead of `import { Model } from 'api-lib/dist/models';`.

This is a kickstart. Sorry, but I cannot keep supporting other options if this doesn't work, because is not the supported way to use `ng-swagger-gen`.
