### ISSUE TITLE
RxJs needs to be updated to work with Angular 6

### ISSUE THREAD

**Issue by tdbrian** [cyclosproject/ng-swagger-gen#53]
Generated service files throw errors "has no exported member" when running Angular CLI v6 due to RxJs upgrade and import changes.

**Comment by luisfpg** [comment]
For now, you can just install the `rxjs-compat`module.
Will be fixed in 0.12, but we're still defining the best solution.
We could either:

- Start depending on Angular 6 / RxJS 6 and change dependencies;
- Add a configuration key in ng-swagger-gen.json to whether generate compatibility imports (to work with RxJs 5.x), having RxJs 6 as default.

**Comment by luisfpg** [comment]
Actually, to follow semver, and to reflect the status of the project, the new version will be 1.0.0 instead of 0.12.
