### ISSUE TITLE
We can generate reactive forms

### ISSUE THREAD

**Issue by ganqqwerty** [cyclosproject/ng-swagger-gen#64]
Reactive forms consist of two pieces: the html and the typescript with `FormGroup`/`FormControl`/`FormBuilder` calls. I think we have enough data to generate the ts part from swagger definition.

What do you think, can I try to implement this?

**Comment by luisfpg** [comment]
I'm starting to think that it would be better to have separated modules to ng-swagger-gen, so that each module could generate things like:

- Model examples (which we are still working on them)
- Reactive forms
- Test mocks

I think now that the ng-swagger-gen core should be leaner, to avoid too much maintenance.
For example, we already had at least 2 major breakages with Angular changes: Http to HttpClient and RxJs 5 to 6. What if the forms module change? Or Jasmine? So, they would affect only the corresponding generation modules.

We'll probably need a few more days to come with a solution for this.

**Comment by ganqqwerty** [comment]
I agree with this completely!

**Comment by luisfpg** [comment]
Sorry, this never got into ng-swagger-gen, and there's no viable resources to implement it.
