### ISSUE TITLE
OpenAPI 3.0 support?

### ISSUE THREAD

**Issue by 7opf** [cyclosproject/ng-swagger-gen#73]
This is a fantastic module and would love to see support for this. I'd be happy to contribute if there is any ongoing work.

**Comment by luisfpg** [comment]
Eventually, yes, OpenAPI 3 will be supported.
However, we have some internal blockers, as the main purpose of ng-swagger-gen conception was to generate clients for [Cyclos](https://www.cyclos.org) API. And the [Cyclos API](https://demo.cyclos.org/api) is very large, to the point that we internally generate a single YAML from several fragments of YAML, because the entire descriptor has 1.1 MB (1.5MB when converted to JSON).
So, when we are ready to migrate Cyclos API to OpenAPI 3, we will work on ng-swagger-gen at the same time, but I don't have any ETA.

**Comment by dimakuba** [comment]
Hi, any updates?

**Comment by luisfpg** [comment]
There's another project for OpenAPI 3: https://github.com/cyclosproject/ng-openapi-gen
